name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/smile_transparent.png
     - assets/images/1.smile.png
     - assets/images/2.smile.png
     - assets/images/3.smile.png
     - assets/images/4.smile.png
     - assets/images/5.smile.png
     - assets/images/6.smile.png
     - assets/images/7.smile.png
     - assets/images/8.smile.png
     - assets/images/9.smile.png
     - assets/images/10.smile.png
     - assets/images/11.smile.png
     - assets/images/12.smile.png
